const DATA_ERROR_CODE = 400;
const FORBIDDEN_ERROR_CODE = 403;
const NOT_FOUND_ERROR_CODE = 404;
const DEFAULT_ERROR_CODE = 500;

module.exports = {
  DATA_ERROR_CODE, FORBIDDEN_ERROR_CODE, NOT_FOUND_ERROR_CODE, DEFAULT_ERROR_CODE,
};
